apiVersion: v1
kind: Service
metadata:
  name: zwitscher-eureka
  labels:
    zwitscher: eureka
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8761
  selector:
    zwitscher: eureka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-eureka
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        zwitscher: eureka
    spec:
      containers:
      - name: zwitscher-eureka
        image: "qaware-oss-docker-registry.bintray.io/zwitscher/zwitscher-eureka:1.1.0"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8761
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8761
          timeoutSeconds: 30
        env:
        - name: JAVA_OPTS
          value: -Xmx128m
