zwitschereureka:
  image: "zwitscher-eureka:1.2.0"
  hostname: zwitschereureka
  environment:
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9761 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8761:8761"